### ISSUE TITLE
Three Quotes

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#65]
I'm loving this quotes pattern from Leven:

![image](https://user-images.githubusercontent.com/4550351/82166895-56e1ae00-98fd-11ea-8c93-d32d27249261.png)

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":33.33} -->
<div class="wp-block-column" style="flex-basis:33.33%"><!-- wp:heading {"textColor":"foreground-dark"} -->
<h2 class="has-foreground-dark-color has-text-color">What Our Customers are Saying</h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"width":66.66} -->
<div class="wp-block-column" style="flex-basis:66.66%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"textColor":"foreground-light","fontSize":"small"} -->
<p class="has-foreground-light-color has-text-color has-small-font-size"><strong>Beverly Mattingdale</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"has-huge-font-size","textColor":"foreground-dark"} -->
<p class="has-huge-font-size has-foreground-dark-color has-text-color">“<em>The audio quality is noticably more amazing than everything else in my studio!” </em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"textColor":"foreground-light","fontSize":"small"} -->
<p class="has-foreground-light-color has-text-color has-small-font-size"><strong>Jefferson Thorpe</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"has-huge-font-size","textColor":"foreground-dark"} -->
<p class="has-huge-font-size has-foreground-dark-color has-text-color"><em>“I was instantly blown away by their sound design and consistency.” </em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"textColor":"foreground-light","fontSize":"small"} -->
<p class="has-foreground-light-color has-text-color has-small-font-size"><strong>Calvin Tristan</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"has-huge-font-size","textColor":"foreground-dark"} -->
<p class="has-huge-font-size has-foreground-dark-color has-text-color"><em>“Utterly impressive—nothing more needs to be said about these folks.”</em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by iamtakashi** [comment]
I think it would be better if the italic text is slightly smaller. It looks good in Levens, but it appeared to be too big to be useful with other themes. How about not using those theme defined preset sizes?

Can we avoid using theme defined colour name like `"textColor":"foreground-light"`? Also, there is an extra, empty paragraph.

**Comment by alaczek** [comment]
I fiddled with it, and this is hard to nail down not knowing if the font used is going to be a serif or sans-serif. When I switched the font size to default, and then picked a theme that uses serif for body it was too small. I think I'm gonna need to use a custom font-size here of 20, which still feels a bit on the small size for serifs but looks much better with sans-serifs.

This is what it looks like with sans-serifs and font-size 20px:

![image](https://user-images.githubusercontent.com/4550351/82507653-3c4e4580-9b46-11ea-8603-e42ef3e92b08.png)

This is what it looks like with serifs and font-size 20px:

![image](https://user-images.githubusercontent.com/4550351/82507681-5720ba00-9b46-11ea-9c51-98b6dcef01d5.png)

Here's the updated code for this:
```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":33.33} -->
<div class="wp-block-column" style="flex-basis:33.33%"><!-- wp:heading -->
<h2>What Our Customers are Saying</h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"width":66.66} -->
<div class="wp-block-column" style="flex-basis:66.66%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"style":{"color":{"text":"#666666"},"typography":{"fontSize":16}}} -->
<p class="has-text-color" style="font-size:16px;color:#666666"><strong>Beverly Mattingdale</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":20}}} -->
<p style="font-size:20px"><em>“The audio quality is noticeably more amazing than everything else in my studio!” </em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"style":{"color":{"text":"#666666"},"typography":{"fontSize":16}}} -->
<p class="has-text-color" style="font-size:16px;color:#666666"><strong>Jefferson Thorpe</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":1.4,"fontSize":20}}} -->
<p style="line-height:1.4;font-size:20px"><em>“I was instantly blown away by their sound design and consistency.” </em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"style":{"color":{"text":"#666666"},"typography":{"fontSize":16}}} -->
<p class="has-text-color" style="font-size:16px;color:#666666"><strong>Calvin Tristan</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":20}}} -->
<p style="font-size:20px"><em>“Utterly impressive—nothing more needs to be said about these folks.”</em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```


Also, when it comes to the previews in the editor - are those generated live based on current theme or static screenshots? I'm talking about those:

![image](https://user-images.githubusercontent.com/4550351/82507863-bc74ab00-9b46-11ea-8a09-5a008eb9a72c.png)

**Comment by iamtakashi** [comment]
> This is what it looks like with sans-serifs and font-size 20px

I think this looks much better and would be useful 👍

The names in #666666 would have a contrast issue with a dark theme. What do you think about wrapping the whole thing with a group with some spacers and give a background? Or just simply leaving them without specifying a colour?

> Also, when it comes to the previews in the editor - are those generated live based on current theme or static screenshots?

They are scaled editor view with the activated theme.

**Comment by alaczek** [comment]
If I wrap in a group and give it a white background color, then it would look weird if dropped in a dark theme, no? In this case, I might drop the custom color entirely, even though I really like the subtle difference between testimonials and names :|

But that raises some bigger issues around using custom colors, that are relevant to page layouts too. Many of the designs we already released would look downright ugly in a theme with a dark color scheme. Maybe we should talk about this during team chat tho.

**Comment by alaczek** [comment]
Here's the updated code for posterity:

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":33.33} -->
<div class="wp-block-column" style="flex-basis:33.33%"><!-- wp:heading -->
<h2>What Our Customers are Saying</h2>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"width":66.66} -->
<div class="wp-block-column" style="flex-basis:66.66%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":16}}} -->
<p style="font-size:16px"><strong>Beverly Mattingdale</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":20}}} -->
<p style="font-size:20px"><em>“The audio quality is noticeably more amazing than everything else in my studio!” </em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":16}}} -->
<p style="font-size:16px"><strong>Jefferson Thorpe</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"lineHeight":1.4,"fontSize":20}}} -->
<p style="line-height:1.4;font-size:20px"><em>“I was instantly blown away by their sound design and consistency.” </em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":16}}} -->
<p style="font-size:16px"><strong>Calvin Tristan</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":20}}} -->
<p style="font-size:20px"><em>“Utterly impressive—nothing more needs to be said about these folks.”</em></p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by iamtakashi** [comment]
> If I wrap in a group and give it a white background color, then it would look weird if dropped in a dark theme, no?

I wouldn't mind having a light coloured full-width pattern on a dark theme as long as the pattern looks good. In the end, that's up to the users. I think the important thing is that a pattern should look good on its own with both light and dark themes activated.

I can still see an empty paragraph, could you remove that from the post in the master site?

**Comment by alaczek** [comment]
You are eagle-eyed :) Removed!

**Comment by ianstewart** [comment]
> I can still see an empty paragraph

One thing to watch out for in the editor is the prompt to "Start writing or type / to choose a block" that you'll see on an empty paragraph block.

**Comment by pablohoneyhoney** [comment]
The heading could be bigger to create larger contrast with the content below. 

Or... I actually love the first iteration, does it look so bad with other themes? 

![](https://user-images.githubusercontent.com/4550351/82166895-56e1ae00-98fd-11ea-8c93-d32d27249261.png)

**Comment by alaczek** [comment]
I love the original too! This is how it would look like with the sans-serif fonts though (while keeping the original font size):

Using Alves:
![image](https://user-images.githubusercontent.com/4550351/95405806-7fc61680-0964-11eb-9156-69984c4a22e5.png)

Using Mayland:
![image](https://user-images.githubusercontent.com/4550351/95405857-a7b57a00-0964-11eb-8c33-133c73bdf795.png)

Using Balasana:
![image](https://user-images.githubusercontent.com/4550351/95405942-d92e4580-0964-11eb-8349-149f9219d161.png)


Given this I feel like reducing the font size was the right decision. 

As for the heading size, we could definitely bump that up, although sticking to theme defaults would ensure typographic consistency on the page. If a theme has h2 headings at 34px for example, bumping it to say 42px would really stand out. So there's a balance to strike here between tweaking the pattern and making sure it blends in when inserted on the page.
